INSERT INTO [dbo].[Province] ([ProvinceId],[RegionId],[ProvinceName],[rowguid],[ModifiedDate])
VALUES
	(2,8,'Albacete',NEWID(),GETDATE()),
	(3,10,'Alicante/Alacant',NEWID(),GETDATE()),
	(4,1,'Almería',NEWID(),GETDATE()),
	(1,16,'Araba/Álava',NEWID(),GETDATE()),
	(33,3,'Asturias',NEWID(),GETDATE()),
	(5,7,'Ávila',NEWID(),GETDATE()),
	(6,11,'Badajoz',NEWID(),GETDATE()),
	(7,4,'Balears, Illes',NEWID(),GETDATE()),
	(8,9,'Barcelona',NEWID(),GETDATE()),
	(48,16,'Bizkaia',NEWID(),GETDATE()),
	(9,7,'Burgos',NEWID(),GETDATE()),
	(10,11,'Cáceres',NEWID(),GETDATE()),
	(11,1,'Cádiz',NEWID(),GETDATE()),
	(39,6,'Cantabria',NEWID(),GETDATE()),
	(12,10,'Castellón/Castelló',NEWID(),GETDATE()),
	(51,18,'Ceuta',NEWID(),GETDATE()),
	(13,8,'Ciudad Real',NEWID(),GETDATE()),
	(14,1,'Córdoba',NEWID(),GETDATE()),
	(15,12,'Coruña, A',NEWID(),GETDATE()),
	(16,8,'Cuenca',NEWID(),GETDATE()),
	(20,16,'Gipuzkoa',NEWID(),GETDATE()),
	(17,9,'Girona',NEWID(),GETDATE()),
	(18,1,'Granada',NEWID(),GETDATE()),
	(19,8,'Guadalajara',NEWID(),GETDATE()),
	(21,1,'Huelva',NEWID(),GETDATE()),
	(22,2,'Huesca',NEWID(),GETDATE()),
	(23,1,'Jaén',NEWID(),GETDATE()),
	(24,7,'León',NEWID(),GETDATE()),
	(27,12,'Lugo',NEWID(),GETDATE()),
	(25,9,'Lleida',NEWID(),GETDATE()),
	(28,13,'Madrid',NEWID(),GETDATE()),
	(29,1,'Málaga',NEWID(),GETDATE()),
	(52,19,'Melilla',NEWID(),GETDATE()),
	(30,14,'Murcia',NEWID(),GETDATE()),
	(31,15,'Navarra',NEWID(),GETDATE()),
	(32,12,'Ourense',NEWID(),GETDATE()),
	(34,7,'Palencia',NEWID(),GETDATE()),
	(35,5,'Palmas, Las',NEWID(),GETDATE()),
	(36,12,'Pontevedra',NEWID(),GETDATE()),
	(26,17,'Rioja, La',NEWID(),GETDATE()),
	(37,7,'Salamanca',NEWID(),GETDATE()),
	(38,5,'Santa Cruz de Tenerife',NEWID(),GETDATE()),
	(40,7,'Segovia',NEWID(),GETDATE()),
	(41,1,'Sevilla',NEWID(),GETDATE()),
	(42,7,'Soria',NEWID(),GETDATE()),
	(43,9,'Tarragona',NEWID(),GETDATE()),
	(44,2,'Teruel',NEWID(),GETDATE()),
	(45,8,'Toledo',NEWID(),GETDATE()),
	(46,10,'Valencia/València',NEWID(),GETDATE()),
	(47,7,'Valladolid',NEWID(),GETDATE()),
	(49,7,'Zamora',NEWID(),GETDATE()),
(50,2,'Zaragoza',NEWID(),GETDATE());