INSERT INTO [dbo].[Region]([RegionId], [RegionName],[rowguid],[ModifiedDate])
VALUES
	(1,'Andalucía',NEWID(),GETDATE()),
	(2,'Aragón',NEWID(),GETDATE()),
	(3,'Asturias, Principado de',NEWID(),GETDATE()),
	(4,'Balears, Illes',NEWID(),GETDATE()),
	(5,'Canarias',NEWID(),GETDATE()),
	(6,'Cantabria',NEWID(),GETDATE()),
	(7,'Castilla y León',NEWID(),GETDATE()),
	(8,'Castilla - La Mancha',NEWID(),GETDATE()),
	(9,'Catalunya',NEWID(),GETDATE()),
	(10,'Comunitat Valenciana',NEWID(),GETDATE()),
	(11,'Extremadura',NEWID(),GETDATE()),
	(12,'Galicia',NEWID(),GETDATE()),
	(13,'Madrid, Comunidad de',NEWID(),GETDATE()),
	(14,'Murcia, Región de',NEWID(),GETDATE()),
	(15,'Navarra, Comunidad Foral de',NEWID(),GETDATE()),
	(16,'País Vasco',NEWID(),GETDATE()),
	(17,'Rioja, La',NEWID(),GETDATE()),
	(18,'Ceuta',NEWID(),GETDATE()),
(19,'Melilla',NEWID(),GETDATE());